default: -r features/step_definitions -r features/support features
production:  --profile default ENVIRONMENT="production"
parallel: --profile default --tags ~@wip 
staging: --profile default ENVIRONMENT="staging"
